### ISSUE TITLE
Types for dataset and projectId are missing

### ISSUE THREAD

**Issue by harshmalviya** [coreyward/react-portable-text#14]
While using react-portable-text in next js typescript environment it throws an error for passing dataset and projectId as it is not expected in props in the definition of the component. 
![image](https://user-images.githubusercontent.com/73441485/150298526-cb812d12-6e98-481a-b902-535db0200ff8.png)
Attached an image for adjustment.

**Comment by WavingCatDevs** [comment]
on #15 it fixes this, but it hasn't been merged yet

**Comment by coreyward** [comment]
Fixed in #15 and released in 0.4.1. 👍
