### ISSUE TITLE
PortableText

### ISSUE THREAD

**Issue by labeshgarg** [coreyward/react-portable-text#22]
The space between the paragraphs are not displaying.

**Comment by coreyward** [comment]
What space between paragraphs? Are you referring to your CSS styles?

**Comment by labeshgarg** [comment]
<img width="503" alt="Screenshot 2022-08-03 at 1 08 49 AM" src="https://user-images.githubusercontent.com/102824517/182459570-5078e6d8-6955-4899-9799-8b7c4dd711e2.png">
There is a space between the two, but when it is being rendered on the page, there isn't. 
I haven't styled anything for the p elements. I am not getting why this is happening.
<img width="587" alt="Screenshot 2022-08-03 at 1 09 18 AM" src="https://user-images.githubusercontent.com/102824517/182459770-3dabfd69-f1b2-42ac-9341-18a49aa615ce.png">

**Comment by coreyward** [comment]
Sanity does not include any spacing or layout information on blocks. It is up to you to include CSS to style things how you'd like. Can you share what the actual JSON portable text content is for this field, and what the markup is in your app?
