### ISSUE TITLE
Empty lines are not rendered...

### ISSUE THREAD

**Issue by fuhrthom** [coreyward/react-portable-text#25]
How can I render empty <p></p> as newline? Tried to overwrite the 'normal' serializer, but it renders all p tags, dont know how to render new lines....

**Comment by coreyward** [comment]
This will depend on the shape of the input (i.e. the block type and data) and how @sanity/block-content-to-react handles it by default. This library really just helps make it easier to use @sanity/block-content-to-react—it doesn't override its behavior.
